# Generated by Django 3.0.7 on 2022-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usarid', models.IntegerField(max_length=5)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=80)),
                ('contraseña', models.SmallIntegerField(max_length=20)),
            ],
        ),
    ]
